name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (local use, not for EC2)
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REMOTE_APP_DIR="${{ secrets.REMOTE_APP_DIR }}"
            REPO_URL="${{ secrets.REPO_URL }}"

            if [ ! -d "$REMOTE_APP_DIR" ]; then
              echo "Directory does not exist. Cloning..."
              git clone "$REPO_URL" "$REMOTE_APP_DIR"
            fi

            echo "Marking safe directory for Git"
            git config --global --add safe.directory "$REMOTE_APP_DIR"

            echo "Pulling latest changes..."
            cd "$REMOTE_APP_DIR"
            git pull

            echo "Setting permissions..."
            mkdir -p "$REMOTE_APP_DIR/logs"
            chmod 775 "$REMOTE_APP_DIR/logs"
            chown -R www-data:www-data "$REMOTE_APP_DIR"
            chmod -R 775 "$REMOTE_APP_DIR"

            echo "✅ Deployment completed"
