name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (local use, not for EC2)
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            REMOTE_APP_DIR="${{ secrets.REMOTE_APP_DIR }}"
            REPO_URL="${{ secrets.REPO_URL }}"

            if [ ! -d "$REMOTE_APP_DIR" ]; then
              echo "Directory does not exist. Cloning..."
              sudo git clone "$REPO_URL" "$REMOTE_APP_DIR"
            fi

            echo "Pulling latest changes..."
            cd "$REMOTE_APP_DIR"
            sudo git pull

            if [ -f "composer.json" ]; then
              echo "Running composer install..."
              composer install --no-dev --optimize-autoloader
            fi

            if [ -f "package.json" ]; then
              echo "Running npm install..."
              npm install
            fi

            echo "✅ Deployment completed"
